---
_title: 00_UKB
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressWarnings(library(dplyr))
suppressWarnings(library(ggplot2))
suppressWarnings(library(readr))
suppressWarnings(library(xtable))
suppressWarnings(library(qvalue))
suppressWarnings(library(ggcorrplot))
suppressWarnings(source("_helpers_misc.R"))
suppressWarnings(source("_helpers_results_files.R"))
suppressWarnings(source("_helpers_file_logic.R"))
suppressWarnings(source("_helpers_plots.R"))
suppressWarnings(source("_helpers_qq.R"))
suppressWarnings(source("_helpers_scatter.R"))
suppressWarnings(source("_helpers_comparison_plots.R"))
suppressWarnings(source("_helpers_mt_analysis.R"))
suppressWarnings(source("_helpers_simulations_processing.R"))
```

# Setup

```{r folders, echo=FALSE}
results_dir <- 'results'
if(!dir.exists(results_dir)) dir.create(results_dir)

plots_dir_ <- file.path(results_dir, "plots")
if(!dir.exists(plots_dir_)) dir.create(plots_dir_)

plots_dir <- file.path(plots_dir_, "ukb")
if(!dir.exists(plots_dir)) dir.create(plots_dir)
```

```{r preliminaries, echo=FALSE, cache=TRUE}
gencode <- read.delim("data/gencode.v19.flat.txt.gz")
names <- ukb_file_metadata_smt_mt("data/ukb/ukb_column_to_name.csv", "data/ukb/smt_ukb_ccn_30", "data/ukb/mt_ukb_cn30")
```

# MT-PrediXcan is better: UKB cholesterol

```{r ukb_cholesterol_data, echo=FALSE, cache=TRUE}
chol_predixcan <- load_folder("data/ukb/predixcan",".txt", white_list=c("UKB_High_cholesterol")) %>% rename(tissue=model)
chol_multi_predixcan <- suppressMessages(readr::read_tsv("data/ukb/mt_ukb_cn30/UKB_High_cholesterol_c20002_1536.txt"))
```

```{r ukb_cholesterol_plot, echo=FALSE, cache=TRUE}
(function(){
  (qq_plot_mt_vs_all_univariate(chol_multi_predixcan, chol_predixcan, "Whole_Blood") + 
     ggplot2::ggtitle("Significance QQ-Plot", subtitle="Cholesterol in UK Biobank")) %>%
    save_png(file.path(plots_dir, "UKB_Cholesterol_qq.png"), 600, 600)
  
  (significant_discoveries_bar_plot(chol_multi_predixcan, chol_predixcan, "Whole_Blood") + 
     ggplot2::ggtitle("Number of significant genes", subtitle="Cholesterol in UK Biobank")) %>%
    save_png(file.path(plots_dir, "UKB_Cholesterol_significant_bars.png"), 600, 600)
})()
```

```{r ukb_cholesterol_plot_supp, echo=FALSE, cache=TRUE}
(function(){
  y1 <- c(
    get_fdr_significant_gene_count_(chol_predixcan %>% filter(tissue == "Whole_Blood"), 0.05),
    get_fdr_significant_gene_count_(chol_predixcan, 0.05),
    get_fdr_significant_gene_count_(chol_multi_predixcan, 0.05)
  )
  label1 <- rep("FDR<0.05", length(y1))
  y2 <- c(
    get_fdr_significant_gene_count_(chol_predixcan %>% filter(tissue == "Whole_Blood"), 0.01),
    get_fdr_significant_gene_count_(chol_predixcan, 0.01),
    get_fdr_significant_gene_count_(chol_multi_predixcan, 0.01)
  )
  label2 <- rep("FDR<0.01", length(y2))
  y3 <- c(
    get_fdr_significant_gene_count_(chol_predixcan %>% filter(tissue == "Whole_Blood"), 1e-4),
    get_fdr_significant_gene_count_(chol_predixcan, 1e-4),
    get_fdr_significant_gene_count_(chol_multi_predixcan, 1e-4)
  )
  label3 <- rep("FDR<1e-4", length(y3))
  y <- c(y1,y2,y3)
  label <- factor(c(label1, label2, label3), levels=c("FDR<0.05", "FDR<0.01","FDR<1e-4"))
  (significant_discoveries_bar_plot_(y, "Whole_Blood", label=label) + 
     ggplot2::ggtitle("Number of significant genes", subtitle="Cholesterol in UK Biobank") +
     ggplot2::facet_wrap(~label, ncol=3, scales="free"))  %>%
    save_png(file.path(plots_dir, "UKB_Cholesterol_significant_bars_fdr.png"), 500, 1500)
})()
```

```{r cholesterol_tables, echo=FALSE, cache=TRUE}
(function() {
  p <- chol_predixcan %>% 
    dplyr::inner_join(gencode, by="gene") %>% 
    dplyr::select(gene, gene_name, tissue, zscore, pvalue) %>%
    dplyr::arrange(pvalue) %>%
    dplyr::filter(pvalue < 0.05/nrow(chol_predixcan))
  p %>% p_save_delim(file.path(results_dir, "ukb_high_cholesterol_predixcan_significant.txt"))
  
  mtp <- chol_multi_predixcan %>% 
    dplyr::inner_join(gencode, by="gene") %>% 
    dplyr::select(gene, gene_name, pvalue) %>%
    dplyr::arrange(pvalue) %>%
    dplyr::filter(pvalue < 0.05/nrow(chol_multi_predixcan))
  mtp %>%  p_save_delim(file.path(results_dir, "ukb_high_cholesterol_multixcan_significant.txt"))
  
  #pg <- p$gene %>% unique()
  #mtpg <- mtp$gene %>% unique()
  #p %>% filter(gene %in% pg[!(pg %in% mtpg)]) %>% arrange(pvalue)
  #mtp %>% filter(gene %in% mtpg[!(mtpg %in% pg)]) %>% arrange(pvalue)
})()
```

```{r scatter_plots, echo=FALSE, cache=TRUE}
(function(){
  selected_ <- c("UKB_High_cholesterol", "UKB_Asthma", "UKB_Trunk_fat_percentage", "UKB_Sleep_duration")
  names_c_ <- names %>% dplyr::filter(name %in% selected_) %>% mutate(name = factor(name, levels=selected_)) %>% arrange(name)
  
  (do_scatter_plot_mt_vs_smt (names_c_) + 
    ggtitle("S-MultiXcan can infer individual-level MultiXcan") + 
    facet_wrap(~phenotype, scales="fixed", ncol=4)) %>% save_png(file.path(plots_dir, "smt_vs_mt_ukb.png"), height=400, width=1100)
  
  selected_mt_vs_smt <- function(names, selected, title, subtitle, path, columns=4) {
    selected <- gsub("UKB_", "",  selected)
    names_ <- names %>% mutate(name = gsub("UKB_", "", name)) %>% dplyr::filter(name %in% selected) %>% mutate(name = factor(name, levels=selected)) %>% arrange(name)
    (do_scatter_plot_mt_vs_smt (names_) + ggtitle(title, subtitle=subtitle) + facet_wrap(~phenotype, scales="free", ncol =columns)) %>% save_png(path, height=1300, width=1300)
  }

  selected_ <- c("UKB_BMI", "UKB_Body_fat_percentage", "UKB_Hand_grip_strength_left", "UKB_Duration_of_vigorous_activity",
                 "UKB_Bread_intake", "UKB_Fresh_fruit_intake", "UKB_Water_intake", "UKB_Forced_vital_capacity_Best_measure",
                 "UKB_Hayfever_aka_allergic_rhinitis", "UKB_Asthma", "UKB_Age_asthma_diagnosed", "UKB_Eczema_aka_dermatitis",
                 "UKB_Fluid_intelligence_score", "UKB_Neuroticism_score", "UKB_Diabetes", "UKB_Age_diabetes_diagnosed")
  selected_mt_vs_smt(names, selected_, "UK Biobank", "Miscellaneous Traits", file.path(plots_dir, "smt_vs_mt_ukb_supp.png"))
  
  selected_2_ <- c("UKB_Duration_of_vigorous_activity", "UKB_Bread_intake", "UKB_Forced_vital_capacity_Best_measure",
                 "UKB_Hayfever_aka_allergic_rhinitis", "UKB_Asthma", "UKB_Eczema_aka_dermatitis",
                 "UKB_Neuroticism_score", "UKB_Diabetes", "UKB_Age_diabetes_diagnosed")
  selected_mt_vs_smt(names, selected_2_, "UK Biobank", "Miscellaneous Traits", file.path(plots_dir, "smt_vs_mt_ukb_supp_2.png"), columns = 3)
})()
```

# MT-PrediXcan vs PrediXcan

```{r mt_analysis, echo=FALSE, cache=TRUE}
analisis_results <- get_mt_predixcan_analysis("data/ukb/mt_ukb_cn30", "data/ukb/predixcan")#, verbose=TRUE)
```

```{r mt_metaxcan_analysis_output, echo=FALSE, cache=TRUE}
stats <- analisis_results$stats
p_save_delim(stats, file.path(results_dir, "ukb_multixcan_stats.txt"))

plot_n_significant_comparison_i(stats, threshold=800) %>% save_png( file.path(plots_dir, "ukb_mt_vs_p_number_significant.png"), height=800, width=800)
plot_n_significant_only_comparison_i(stats, threshold=800) %>% save_png( file.path(plots_dir, "ukb_mt_only_vs_p_only_number_significant.png"), height=800, width=800)

p_significant <- analisis_results$p_significant %>% inner_join(gencode, by="gene") %>% select(phenotype, model, gene, gene_name, zscore,  pvalue,  n_samples)
p_save_delim(p_significant, file.path(results_dir, "ukb_p_significant.txt"))

mt_significant <- analisis_results$mt_significant %>% inner_join(gencode, by="gene") %>% select(phenotype, gene, gene_name, pvalue, n_models, n_used, n_samples)
p_save_delim(mt_significant, file.path(results_dir, "ukb_multixcan_significant.txt"))
```


With qvalues!

```{r mt_analysis_q, echo=FALSE, cache=TRUE}
analisis_results_q <- get_mt_predixcan_analysis("data/ukb/mt_ukb_cn30", "data/ukb/predixcan", verbose=TRUE, stats_f_=get_p_mt_stats_q_)
```

```{r mt_metaxcan_analysis_output_q, echo=FALSE, cache=TRUE}
stats_q <- analisis_results_q$stats
p_save_delim(stats_q, file.path(results_dir, "ukb_multixcan_stats_q.txt"))

mt_significant_q <- analisis_results_q$mt_significant %>% inner_join(gencode, by="gene") %>% select(phenotype, gene, gene_name, pvalue, n_models, n_used, n_samples)
p_save_delim(mt_significant_q, file.path(results_dir, "ukb_multixcan_significant_q.txt"))
```

```{r, mt_individual_suspicious}
mt_individual_suspicious <- get_mt_individual_suspicious ("data/ukb/mt_ukb_cn0", "data/ukb/mt_ukb_cn30",) %>% arrange(-n_flagged) %>% mutate(percent=n_flagged*100/n_significant)
p_save_delim(mt_individual_suspicious, file.path(results_dir, "ukb_individual_flagged.txt"))
```

```{r smt_conservative, echo=FALSE, cache=TRUE}
mt_vs_smt_summary <-  get_mt_vs_smt_summary_(names)
(plot_conservative_fraction(mt_vs_smt_summary) + 
    ggplot2::ggtitle("Underestimated Significant Associations", subtitle ="Traits in UK Biobank") +
    ggplot2::xlab("Proportion of underestimated signals") +
    ggplot2::ylab("Number of traits") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 3))) %>%
  save_png(file.path(plots_dir, "proportion_underestimated_ukb.png"), 700, 700)
```



```{r multixcan_global_stats, echo=FALSE, cache=TRUE}
(function(){
  d <- stats %>% filter(n_multixcan_significant > 0 | n_predixcan_significant > 0)
  m_wins <- d %>% filter(n_multixcan_significant > n_predixcan_significant) %>% nrow()
  p_wins <- d %>% filter(n_multixcan_significant < n_predixcan_significant) %>% nrow()
  m_tie <- d %>% filter(n_multixcan_significant == n_predixcan_significant) %>% nrow()
  m_none <- stats %>% filter(n_multixcan_significant ==0, n_predixcan_significant == 0) %>% nrow()
  m_how_many <- d %>% mutate(h = n_multixcan_significant - n_predixcan_significant) %>% .$h %>% median()
  m_overlap <- d %>% filter(n_multixcan_significant > 0, n_predixcan_significant > 0) %>%mutate(nm = n_multixcan_significant - n_multixcan_only, np = n_predixcan_significant - n_predixcan_only) %>%
    mutate(overlapi = pmin(nm,np), overlapa = pmin(n_multixcan_significant, n_predixcan_significant)) %>% mutate(of = overlapi*100.0/overlapa) %>% #mutate(of = pmin(of, 100)) %>%
    .$of %>% median()

  r <- data.frame(field=c("MultiXcan wins", "Ties", "PrediXcan wins", "No detection", "MultiXcan Median Improvement", "Median overlap"),
                  value=c(m_wins, m_tie, p_wins,  m_none,  m_how_many, m_overlap),
    stringsAsFactors = FALSE)

  r %>% xtable(type = "latex") %>% print(file = file.path(results_dir, "ukb_summary.tex"))
})()
```

```{r height_tendency, echo=FALSE, cache=TRUE}
(function(){
  mt_30_ <- "data/additional/ukb_height/ukb_height__ccn_30.txt.gz" %>% load_mt_("multixcan", "condition number 30") %>% select(gene, pvalue, label, n_models)
  mt_0_ <- "data/additional/ukb_height/ukb_height__ccn_0.txt.gz" %>% load_mt_("multixcan", "None") %>% select(gene, pvalue, label, n_models)

  d <- rbind(mt_30_, mt_0_) %>% mutate(s = -log10(pvalue))

  p <- ggplot(d) + geom_smooth(aes(x=n_models, y=s, color=label)) +
    paper_plot_theme_a() + xlab("Number of  components used") + ylab(expression(Significance~(-log10(pvalue)))) +
    ggtitle("Effect of PCA Regularization", subtitle="Height") + 
    guides(color=guide_legend(title="Regularization"))
  p %>% save_png(file.path(plots_dir, "ukb_height_pve_tendency_2.png"), 800, 800)
})()
```


```{r correlation, echo=FALSE, cache=TRUE}
(function(){
  d <- read.delim("data/correlation/correlation_median.txt.gz")
  d[is.na(d)] <- 0
  rownames(d) <- colnames(d)
  p <- ggcorrplot(d, hc.order =TRUE, outline.col="white", type="lower", colors = c("#6D9EC1", "white", "#E46726")) +
    ggtitle("Median Predicted Expression Correlation", subtitle="UK Biobank")
  p %>% save_png(file.path(plots_dir, "ukb_correlation.png"), 800, 800) 
})()
```