---
title: "01_GWAS.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressWarnings(library(dplyr))
suppressWarnings(library(ggplot2))
suppressWarnings(library(readr))
suppressWarnings(library(ggpubr))
suppressWarnings(library(qvalue))
suppressWarnings(library(xtable))
suppressWarnings(source("_helpers_misc.R"))
suppressWarnings(source("_helpers_file_logic.R"))
suppressWarnings(source("_helpers_plots.R"))
suppressWarnings(source("_helpers_mt_analysis.R"))
suppressWarnings(source("_helpers_qq.R"))
suppressWarnings(source("_helpers_comparison_plots.R"))
```

# Preliminaries

```{r folders, echo=FALSE}
results_dir <- 'results'
if(!dir.exists(results_dir)) dir.create(results_dir)

plots_dir_ <- file.path(results_dir, "plots")
if(!dir.exists(plots_dir_)) dir.create(plots_dir_)

plots_dir <- file.path(plots_dir_, "gwas")
if(!dir.exists(plots_dir)) dir.create(plots_dir)
```

```{r preliminaries, echo=FALSE, cache=TRUE}
phenos <- read.delim("data/phenos.txt")
pheno_whitelist <- phenos %>% dplyr::filter(!ignore) %>% .$pheno

selected_gwas <- read.delim("data/selected_gwas.txt")
pheno_info <- read_tsv("data/gene2pheno_info.txt")
```

```{r pheno_info, echo=FALSE, cache=TRUE}
pheno_info %>% select(consortium, name, tag, sample_size, population, portal, pubmed_paper_link) %>% p_save_delim(file.path(results_dir, "gwas_traits.txt"))
```

# GWAS results comparison

```{r mt_metaxcan_analysis, echo=FALSE, cache=TRUE}
analisis_results <- get_mt_metaxcan_analysis("data/gene2pheno_dev_hm_1.5", "data/smt/smt_gwas_ccn_30")#, verbose=TRUE)
```

```{r mt_metaxcan_analysis_output, echo=FALSE, cache=TRUE}
stats <- pheno_info %>% select(tag, consortium, name) %>% inner_join(analisis_results$stats, by="tag")
p_save_delim(stats, file.path(results_dir, "gwas_smultixcan_stats.txt"))

plot_n_significant_comparison(stats, threshold=400) %>% save_png( file.path(plots_dir, "smt_vs_sp_number_significant.png"), height=800, width=800)
plot_n_significant_only_comparison(stats) %>% save_png( file.path(plots_dir, "smt_only_vs_sp_only_number_significant.png"), height=800, width=800)
 
sp_significant <- pheno_info %>% select(tag, consortium, name) %>% 
  inner_join(analisis_results$sp_significant, by=c("tag"="phenotype")) %>%
  select(consortium, name, tag, gene, gene_name, model,  zscore, pval) %>% rename(pvalue=pval)
  #select(-p_smr,-p_heidi,-twas_pvalue,-p_h0, -p_h1, -p_h2, -p_h3, -p_h4, -pred_perf_r2, -pred_perf_pval, -pred_perf_qval, -n_snps_used, -n_snps_model) %>% rename(pvalue=pval)
p_save_delim(sp_significant, file.path(results_dir, "gwas_sp_significant.txt"))

smt_significant <- pheno_info %>% select(tag, consortium, name) %>% 
  inner_join(analisis_results$smt_significant, by=c("tag"="phenotype")) %>%
  select(-eigen_max, -eigen_min, -eigen_min_kept, -z_min, -z_max, -z_mean, -z_sd, -tmi, -status)
p_save_delim(smt_significant, file.path(results_dir, "gwas_smultixcan_significant.txt"))

```

```{r mt_metaxcan_analysis_q, echo=FALSE, cache=TRUE}
analisis_results_q <- get_mt_metaxcan_analysis("data/gene2pheno_dev_hm_1.5", "data/smt/smt_gwas_ccn_30", stats_f_=get_m_smt_stats_q_, 
                                     spredixcan_significant_m=spredixcan_significant_gtex_q_, smt_significant_m=smt_significant_minus_suspicious_q_, verbose = TRUE)
```

```{r mt_metaxcan_analysis_output_q, echo=FALSE, cache=TRUE}
stats_q <- pheno_info %>% select(tag, consortium, name) %>% inner_join(analisis_results_q$stats, by="tag")
p_save_delim(stats_q, file.path(results_dir, "gwas_smultixcan_stats_q.txt"))

smt_significant_q <- pheno_info %>% select(tag, consortium, name) %>% 
  inner_join(analisis_results_q$smt_significant, by=c("tag"="phenotype")) %>%
  select(-eigen_max, -eigen_min, -eigen_min_kept, -z_min, -z_max, -z_mean, -z_sd, -tmi, -status)
p_save_delim(smt_significant_q, file.path(results_dir, "gwas_smultixcan_significant_q.txt"))

```

# Example trait: Schizophrenia


```{r scz2_data, echo=FALSE, cache=TRUE}
scz2_predixcan <- suppressMessages(readr::read_tsv("data/gene2pheno_dev_hm_1.5/pgc.scz2.txt")) %>% select(gene=gene, gene_name=gene_name,tissue=model,pvalue=pval)
scz2_multi_predixcan <- suppressMessages(readr::read_tsv("data/smt/smt_gwas_ccn_30/pgc.scz2_ccn_30.txt"))
```

```{r scz2_plot, echo=FALSE, cache=TRUE}
(function(){
  # a <- qq_plot_mt_vs_all_univariate(scz2_multi_predixcan, scz2_predixcan, "Brain_Cerebellum") +ggtitle("Significance QQ-Plot", subtitle="PGC Schizophrenia")
  # b <- significant_discoveries_bar_plot(scz2_multi_predixcan, scz2_predixcan, "Brain_Cerebellum") + ggplot2::ggtitle("Significant Associations", subtitle="PGC Schizophrenia")
  # ggarrange(a, b, labels = c("a", "b"), ncol = 2, nrow = 1, font.label = list(size = 30, face = "bold")) %>% save_png(file.path(plots_dir, "PGC_scz2_supp_signif.png"), 600, 1200)
  
  # Plot only those unsuspicious results
  scz2_multi_predixcan_ <- scz2_multi_predixcan %>% smultixcan_remove_suspicious()

  (qq_plot_mt_vs_all_univariate(scz2_multi_predixcan_, scz2_predixcan, "Brain_Cerebellum", "S-MultiXcan", "S-PrediXcan") +
    ggtitle("Significance QQ-Plot", subtitle="PGC Schizophrenia")) %>% save_png(file.path(plots_dir, "PGC_scz2_qq.png"), 600, 600)
  
  (significant_discoveries_bar_plot(scz2_multi_predixcan_, scz2_predixcan, "Brain_Cerebellum", "S-MultiXcan", "S-PrediXcan") + 
      ggplot2::ggtitle("Number of significant genes", subtitle="PGC Schizophrenia")) %>% save_png(file.path(plots_dir, "PGC_scz2_significant_bars.png"), 600, 600)
})()
```

```{r multixcan_global_stats, echo=FALSE, cache=TRUE}
(function(){
  d <- stats %>% filter(n_smultixcan_significant > 0 | n_spredixcan_significant > 0)
  m_wins <- d %>% filter(n_smultixcan_significant > n_spredixcan_significant) %>% nrow()
  p_wins <- d %>% filter(n_smultixcan_significant < n_spredixcan_significant) %>% nrow()
  m_tie <- d %>% filter(n_smultixcan_significant == n_spredixcan_significant) %>% nrow() 
  m_none <- stats %>% filter(n_smultixcan_significant ==0, n_spredixcan_significant == 0) %>% nrow()
  m_how_many <- d %>% mutate(h = n_smultixcan_significant - n_spredixcan_significant) %>% .$h %>% median()
  m_overlap <- d %>% filter(n_smultixcan_significant > 0, n_spredixcan_significant > 0) %>%mutate(nm = n_smultixcan_significant - n_smultixcan_only, np = n_spredixcan_significant - n_spredixcan_only) %>%
    mutate(overlapi = pmin(nm,np), overlapa = pmin(n_smultixcan_significant, n_spredixcan_significant)) %>% mutate(of = overlapi*100.0/overlapa) %>% #mutate(of = pmin(of, 100)) %>% 
    .$of %>% median()
  
  r <- data.frame(field=c("S-MulTixcan wins", "Ties", "S-PrediXcan wins", "No detection", "S-MulTixcan Median Improvement", "Median overlap"),
                  value=c(m_wins, m_tie, p_wins,  m_none,  m_how_many, m_overlap),
    stringsAsFactors = FALSE)
  
  r %>% xtable(type = "latex") %>% print(file = file.path(results_dir, "gwas_summary.tex"))
})()
```