---
title: "04_UKB_Spotlight"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressWarnings(library(dplyr))
suppressWarnings(library(ggplot2))
suppressWarnings(library(readr))
suppressWarnings(source("_helpers_misc.R"))
suppressWarnings(library(xtable))
```

# Preliminaries

```{r folders, echo=FALSE, cache=TRUE}
results_dir <- 'results'
if(!dir.exists(results_dir)) dir.create(results_dir)

plots_dir_ <- file.path(results_dir, "plots")
if(!dir.exists(plots_dir_)) dir.create(plots_dir_)

plots_dir <- file.path(plots_dir_, "ukb")
if(!dir.exists(plots_dir)) dir.create(plots_dir)

gencode <- read.delim("data/gencode.v19.flat.txt.gz")
```


```{r ukb_cholesterol_data, echo=FALSE, cache=TRUE}
chol_p_ <- read_tsv("results/ukb_high_cholesterol_predixcan_significant.txt") %>% rename(model = tissue)
chol_p <- chol_p_ %>% group_by(gene, gene_name) %>% summarise(n_significant_models=n()) %>% inner_join(chol_p_ %>% group_by(gene, gene_name)  %>% top_n(1,pvalue))

chol_mtp <- read_tsv("results/ukb_high_cholesterol_multixcan_significant.txt")

chol_p
chol_mtp
```


```{r CHOL_GENES, echo=FALSE, cache=TRUE}
chol_p_genes <- chol_p$gene_name %>% unique()
chol_mtp_genes <- chol_mtp$gene_name %>% unique()

chol_shared_genes <- chol_p_genes[chol_p_genes %in% chol_mtp_genes]
chol_p_only_genes <- chol_p_genes[!(chol_p_genes %in% chol_mtp_genes)]
chol_mtp_only_genes <- chol_mtp_genes[!(chol_mtp_genes %in% chol_p_genes)]
```

```{r CHOL_SHARED_GENES, echo=FALSE, cache=TRUE}
chol_p %>% filter(gene_name %in% chol_shared_genes)
chol_mtp %>% filter(gene_name %in% chol_shared_genes) %>% select(gene_name, pvalue)
```

```{r CHOL_DIFFERENT_GENES, echo=FALSE, cache=TRUE}
cpo <- chol_p %>% filter(!(gene_name %in% chol_shared_genes))
cmtpo <- chol_mtp %>% filter(!(gene_name %in% chol_shared_genes)) 

cpo %>% select(gene_name, model, pvalue)
cmtpo %>% select(gene_name, pvalue)
```


```{r CHOL_GENE_LISTS, echo=FALSE, cache=TRUE}
fuma_excluded <- readLines("data/fuma_excluded.txt")
chol_genes <- cmtpo$gene %>% remove_id_from_ensemble()
all_genes <- read.delim("data/ukb/mt_ukb_cn30/UKB_High_cholesterol_c20002_1536.txt") %>% .$gene %>% as.character() %>% remove_id_from_ensemble()
all_other_genes <- all_genes[!(all_genes %in% cmtpo$gene)]
all_other_genes <- all_other_genes[!(all_other_genes %in% fuma_excluded)]
write(chol_genes , "results/ukb_cholesterol_genes.txt", sep="\n")
write(chol_genes, "results/ukb_non_cholesterol_genes.txt", sep="\n")
```

# IMPC
```{r impc, echo=FALSE, cache=TRUE}
write(cmtpo$gene_name, "results/ukb_chol_mtonly.txt", sep="\n")
```



# FUMA

Dropped out for now

```{r fuma, echo=FALSE, cache=TRUE, eval=FALSE}
fuma <- read.delim("data/fuma_bmi.txt")
fuma_kegg <- fuma %>% filter(grepl("KEGG", Category)) %>% select(GeneSet, p, genes)
p_save_delim(fuma_kegg, file.path(results_dir, "ukb_fuma_bmi.txt"))

fuma_kegg %>% xtable() %>% 
      print(type="latex", include.rownames=FALSE, file=paste0("results/spotlight_bmi.tex"))
```
